### ISSUE TITLE
Crash with some nilearn stuff

### ISSUE THREAD

**Issue by IKDRipp** [Neurita/pypes#28]
```
	 Executing node main_workflow.spm_mrpet_preproc.petpvc.intensity_norm_gm.norm_img in dir: /home/iripp/data/raw/wd/main_workflow/spm_mrpet_preproc/petpvc/intensity_norm_gm/_diagnosis_healthy_stdpet_session_id_session_0_subject_id_zb_251552/norm_img
171219-14:30:26,208 workflow INFO:
	 [Job finished] jobname: rbvpvc.a491 jobid: 37
171219-14:30:26,276 workflow INFO:
	 Running node "norm_img" ("nipype.interfaces.utility.wrappers.Function").
171219-14:30:26,282 workflow INFO:
	 [Job finished] jobname: gunzip_pet.a490 jobid: 47
171219-14:30:28,323 workflow ERROR:
	 Node norm_img.a492 failed to run on host ferrari.
171219-14:30:28,323 workflow ERROR:
	 Saving crash info to /home/iripp/data/raw/wd/main_workflow/log/crash-20171219-143028-iripp-norm_img.a492-2728bc62-70b8-4417-8914-d7682a9cc766.pklz
Traceback (most recent call last):
  File "/home/iripp/software/nipype/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/iripp/software/nipype/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/home/iripp/software/nipype/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/home/iripp/software/nipype/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/home/iripp/software/nipype/nipype/interfaces/base.py", line 1089, in run
    runtime = self._run_interface(runtime)
  File "/home/iripp/software/nipype/nipype/interfaces/utility/wrappers.py", line 137, in _run_interface
    out = function_handle(**args)
  File "/home/iripp/software/pypes/neuro_pypes/interfaces/nilearn/image.py", line 49, in wrapped
    'decorator.'.format(out_file))
OSError: The file /home/iripp/data/raw/wd/main_workflow/spm_mrpet_preproc/petpvc/_diagnosis_healthy_stdpet_session_id_session_0_subject_id_zb_251552/rbvpvc/rpet_fdg_rbv_pvc_intnormed.nii.gz already exists, please add a presuffix to thedecorator.
```

**Comment by alexsavio** [comment]
Removed this exception, now it is only a warning: 2cae65931d0e56cd4c0ff638471ad906efaa3458
